version: '3' 
services: 
    mariadb:
        image: mariadb:10.6 
        ports:
            - "3307:3306"
        container_name: mariadb
        volumes:
            # 데이터 유지 
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            # 초기 테이블 셋팅, 초기 데이터 삽입
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        environment:
            TZ: Asia/Seoul
            MARIADB_USER: ahyung
            MARIA_DB_PASSWORD: test1234
            MARIADB_ROOT_PASSWORD: 1234
            MARIADB_DATABASE: study_db
        restart: always